"""add sharing and notification/stock/vital models

Revision ID: 4dd8f5e7d5df
Revises: 169c4f3e1695
Create Date: 2025-11-29 12:10:53.575755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd8f5e7d5df'
down_revision: Union[str, Sequence[str], None] = '169c4f3e1695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
