"""initial_public_schema

Revision ID: 844119ee6655
Revises:
Create Date: 2025-12-30 21:58:09.141794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "844119ee6655"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_permission_definitions_code"),
        "permission_definitions",
        ["code"],
        unique=True,
        schema="public",
    )
    op.create_table(
        "tenant_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "total_tenants", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "total_users", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "total_patients", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "total_appointments",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "total_prescriptions",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("license_number", sa.String(length=100), nullable=False),
        sa.Column("schema_name", sa.String(length=100), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "ACTIVE",
                "SUSPENDED",
                "INACTIVE",
                name="tenant_status_enum",
            ),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("max_users", sa.Integer(), nullable=True),
        sa.Column("max_patients", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("license_number"),
        sa.UniqueConstraint("schema_name"),
        schema="public",
    )
    op.create_table(
        "sharing_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("from_tenant_id", sa.UUID(), nullable=False),
        sa.Column("to_tenant_id", sa.UUID(), nullable=False),
        sa.Column("patient_global_id", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_PATIENT",
                "PENDING_ADMIN",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                name="sharing_status_enum",
            ),
            server_default=sa.text("'PENDING_PATIENT'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["to_tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("specialization", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "LOCKED",
                "PASSWORD_EXPIRED",
                name="user_status_enum",
            ),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "must_change_password",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "email_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", "tenant_id", name="uq_users_email_tenant"),
        schema="public",
    )
    op.create_table(
        "email_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("triggered_by_id", sa.UUID(), nullable=True),
        sa.Column("related_user_id", sa.UUID(), nullable=True),
        sa.Column("to", sa.String(length=255), nullable=False),
        sa.Column("template", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["related_user_id"], ["public.users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_id"], ["public.users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        "idx_email_log_template_status",
        "email_logs",
        ["template", "status"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "idx_email_log_to_created",
        "email_logs",
        ["to", "created_at"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_email_logs_created_at"),
        "email_logs",
        ["created_at"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_email_logs_related_user_id"),
        "email_logs",
        ["related_user_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_email_logs_to"),
        "email_logs",
        ["to"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "password_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        "idx_password_history_user_created",
        "password_history",
        ["user_id", "created_at"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_password_history_created_at"),
        "password_history",
        ["created_at"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_password_history_user_id"),
        "password_history",
        ["user_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "patient_shares",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_tenant_id", sa.UUID(), nullable=False),
        sa.Column("target_tenant_id", sa.UUID(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "share_mode",
            sa.Enum("READ_ONLY_LINK", "CREATE_RECORD", name="share_mode_enum"),
            nullable=False,
        ),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "REVOKED", "EXPIRED", name="share_status_enum"),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["public.users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        "idx_patient_share_expires",
        "patient_shares",
        ["expires_at"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "idx_patient_share_token",
        "patient_shares",
        ["token"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_patient_shares_expires_at"),
        "patient_shares",
        ["expires_at"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_patient_shares_patient_id"),
        "patient_shares",
        ["patient_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_patient_shares_source_tenant_id"),
        "patient_shares",
        ["source_tenant_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_patient_shares_target_tenant_id"),
        "patient_shares",
        ["target_tenant_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_patient_shares_token"),
        "patient_shares",
        ["token"],
        unique=True,
        schema="public",
    )
    op.create_table(
        "user_tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tenant_id", name="uq_user_tenant"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_tenants_tenant_id"),
        "user_tenants",
        ["tenant_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_tenants_user_id"),
        "user_tenants",
        ["user_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "patient_share_access_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("share_id", sa.UUID(), nullable=False),
        sa.Column("accessed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "accessed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accessed_by_user_id"], ["public.users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["share_id"], ["public.patient_shares.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_patient_share_access_logs_accessed_at"),
        "patient_share_access_logs",
        ["accessed_at"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_patient_share_access_logs_share_id"),
        "patient_share_access_logs",
        ["share_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "patient_share_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("share_id", sa.UUID(), nullable=False),
        sa.Column("source_tenant_id", sa.UUID(), nullable=False),
        sa.Column("target_tenant_id", sa.UUID(), nullable=False),
        sa.Column("source_patient_id", sa.UUID(), nullable=False),
        sa.Column("target_patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["share_id"], ["public.patient_shares.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_patient_share_links_share_id"),
        "patient_share_links",
        ["share_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_patient_share_links_share_id"),
        table_name="patient_share_links",
        schema="public",
    )
    op.drop_table("patient_share_links", schema="public")
    op.drop_index(
        op.f("ix_public_patient_share_access_logs_share_id"),
        table_name="patient_share_access_logs",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_patient_share_access_logs_accessed_at"),
        table_name="patient_share_access_logs",
        schema="public",
    )
    op.drop_table("patient_share_access_logs", schema="public")
    op.drop_index(
        op.f("ix_public_user_tenants_user_id"),
        table_name="user_tenants",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_user_tenants_tenant_id"),
        table_name="user_tenants",
        schema="public",
    )
    op.drop_table("user_tenants", schema="public")
    op.drop_index(
        op.f("ix_public_patient_shares_token"),
        table_name="patient_shares",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_patient_shares_target_tenant_id"),
        table_name="patient_shares",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_patient_shares_source_tenant_id"),
        table_name="patient_shares",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_patient_shares_patient_id"),
        table_name="patient_shares",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_patient_shares_expires_at"),
        table_name="patient_shares",
        schema="public",
    )
    op.drop_index(
        "idx_patient_share_token", table_name="patient_shares", schema="public"
    )
    op.drop_index(
        "idx_patient_share_expires", table_name="patient_shares", schema="public"
    )
    op.drop_table("patient_shares", schema="public")
    op.drop_index(
        op.f("ix_public_password_history_user_id"),
        table_name="password_history",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_password_history_created_at"),
        table_name="password_history",
        schema="public",
    )
    op.drop_index(
        "idx_password_history_user_created",
        table_name="password_history",
        schema="public",
    )
    op.drop_table("password_history", schema="public")
    op.drop_index(
        op.f("ix_public_email_logs_to"), table_name="email_logs", schema="public"
    )
    op.drop_index(
        op.f("ix_public_email_logs_related_user_id"),
        table_name="email_logs",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_email_logs_created_at"),
        table_name="email_logs",
        schema="public",
    )
    op.drop_index("idx_email_log_to_created", table_name="email_logs", schema="public")
    op.drop_index(
        "idx_email_log_template_status", table_name="email_logs", schema="public"
    )
    op.drop_table("email_logs", schema="public")
    op.drop_table("users", schema="public")
    op.drop_table("sharing_requests", schema="public")
    op.drop_table("tenants", schema="public")
    op.drop_table("tenant_metrics", schema="public")
    op.drop_index(
        op.f("ix_public_permission_definitions_code"),
        table_name="permission_definitions",
        schema="public",
    )
    op.drop_table("permission_definitions", schema="public")
    # ### end Alembic commands ###
